# Nightfox Wezterm Colors
# Style: terafox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/nightfox_wezterm.toml
[colors]
foreground = "#E6EAEA"
background = "#152528"
cursor_bg = "#E6EAEA"
cursor_border = "#E6EAEA"
cursor_fg = "#152528"
selection_bg = "#293e40"
selection_fg = "#E6EAEA"
ansi = ["#2f3239", "#e85c51", "#7aa4a1", "#fda47f", "#5a93aa", "#ad5c7c", "#a1cdd8", "#ebebeb"]
brights = ["#4e5157", "#eb746b", "#8eb2af", "#fdb292", "#73a3b7", "#b97490", "#afd4de", "#eeeeee"]
