require("widgets.top-panel.keyboardlayout")
require("widgets.top-panel.launcher")
require("widgets.top-panel.layoutbox")
require("widgets.top-panel.promptbox")
require("widgets.top-panel.taglist")
require("widgets.top-panel.tasklist")
require("widgets.top-panel.textclock")
