theme_code: &theme_fox
  primary:
    background: '0x192330'
    foreground: '0xafc0d5'
  normal:
    black:   '0x393b44'
    red:     '0xc94f6d'
    green:   '0x4db078'
    yellow:  '0xdbc074'
    blue:    '0x719cd6'
    magenta: '0x8d63cf'
    cyan:    '0x63cdcf'
    white:   '0xdfdfe0'
  bright:
    black:   '0x7f8c98'
    red:     '0xdc5f7e'
    green:   '0x58cd8b'
    yellow:  '0xe8cd82'
    blue:    '0x7daae4'
    magenta: '0x9b70e1'
    cyan:    '0x70dfe1'
    white:   '0xdfdfe0'

colors:
  *theme_fox
