theme_neon: &theme_nightfox
  primary:
    background: '0x192330'
    foreground: '0xcdcecf'
  normal:
    black:   '0x393b44'
    red:     '0xc94f6d'
    green:   '0x81b29a'
    yellow:  '0xdbc074'
    blue:    '0x719cd6'
    magenta: '0x9d79d6'
    cyan:    '0x63cdcf'
    white:   '0xdfdfe0'

  bright:
    black:   '0x475072'
    red:     '0xd6616b'
    green:   '0x58cd8b'
    yellow:  '0xffe37e'
    blue:    '0x84cee4'
    magenta: '0xb8a1e3'
    cyan:    '0x59f0ff'
    white:   '0xf2f2f2'
  indexed_colors:
    - { index: 16, color: '0xf4a261' }
    - { index: 17, color: '0xd67ad2' }

colors:
  *theme_nightfox
