require("ui.widgets.top-panel.keyboardlayout")
require("ui.widgets.top-panel.launcher")
require("ui.widgets.top-panel.layoutbox")
require("ui.widgets.top-panel.promptbox")
require("ui.widgets.top-panel.taglist")
require("ui.widgets.top-panel.tasklist")
require("ui.widgets.top-panel.textclock")
